language: objective-c
osx_image: xcode15.0
script:
- xcodebuild -project src/reminder.xcodeproj -scheme reminder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
